name: akoi
description: install packages using akoi
inputs:
  config:
    description: path to akoi config
    required: true
    default: ${{ github.workspace }}/.akoi.yml
  version:
    description: akoi version
    required: true
    default: v2.2.1 # renovate: depName=suzuki-shunsuke/akoi
  base-directory:
    description: base directory to download packages
    required: true
    default: ${{ github.workspace }}/.akoi
outputs:
  directory:
    description: path to binary directory
runs:
  using: 'node16'
  main: 'dist/index.js'
