name: ts

on:
  push:
    branches:
      - main
      - main-v2
    paths:
      - src/**
      - tests/**
      - '*.json'
      - action.yaml
      - .github/workflows/ts.yaml
  pull_request:
    branches:
      - main
      - main-v2
    paths:
      - src/**
      - tests/**
      - '*.json'
      - action.yaml
      - .github/workflows/ts.yaml

jobs:
  ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn lint
      - run: yarn format-check
      - run: yarn test
      - run: yarn build
      - run: yarn package

      - uses: ./
        id: akoi
      - run: ls -la "${{ steps.akoi.outputs.directory }}"
      # https://github.com/suzuki-shunsuke/github-comment
      - run: github-comment exec -- echo e2e-test passed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
